### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by imm** [blockchain/api-v1-client-ruby#10]
When I'm trying to invoke an API call related to my wallet using `curl` everything is fine. 

Blockchain Wallet Service was installed and launched by command:
```bash
$ blockchain-wallet-service start --port 3000
```

If I type
```bash
$ curl http://localhost:3000/merchant/${ID}/list?password=${PASS}
```
I will get right things.

But it's not working in ruby.

Example of code:
```ruby
require 'blockchain'

wallet = Blockchain::Wallet.new(guid, password,'http://localhost:3000')
wallet.list_addresses #or any other method
```

Result:
```
Blockchain::APIException: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

        from /home/imm/.gem/ruby/2.0/gems/blockchain-2.0.0/lib/blockchain/util.rb:30:in `call_api'
        from /home/imm/.gem/ruby/2.0/gems/blockchain-2.0.0/lib/blockchain/wallet.rb:61:in `list_addresses'
        from (irb):4
        from /usr/bin/irb:12:in `<main>'
```

Is it intended or bugged?

**Comment by Kurity** [comment]
Same for me.

When I call explicitly
```
Blockchain::call_api("merchant/#{@identifier}/list", method: 'get', data: params, base_url: @url)
```
everything works fine and I get a list of addresses. Or when I override `list_addresses` method in my project and use exactly the same method body (e.g. copy/paste it) it works well too. But gem methods don't. I think it ignores passed localhost url, but don't know why.

**Comment by assafY** [comment]
@imm @Kurity 

The api client was recently upgraded - are you still getting this error using the new client?

**Comment by corehook** [comment]
https://github.com/blockchain/api-v1-client-ruby/pull/16
