### ISSUE TITLE
Receive v2 API

### ISSUE THREAD

**Issue by sime** [blockchain/api-v1-client-ruby#3]
This repository is quite clearly labeled v1, and the new receive API is labelled v2 and depends a on new BASE_URL: https://api.blockchain.info/

Will there be a new library or is this the place to provide patches?

**Comment by jackywhlee** [comment]
Would like to hear more about this.

**Comment by tuzzolo** [comment]
Support for Receive v2 API added here: https://github.com/blockchain/api-v1-client-ruby/commit/43a92f0bbe683ba2d7486b033cf8b916019ab618
